{% set version = "1.0.1" %}
{% set gdalversion = "3.3.1" %}

package:
  name: gdal-csharp
  version: {{ version }}

source:
  url: http://download.osgeo.org/gdal/{{ gdalversion }}/gdal-{{ gdalversion }}.tar.xz
  sha256: 48ab00b77d49f08cf66c60ccce55abb6455c3079f545e60c90ee7ce857bccb70

build:
  number: 0

requirements:
  build:
    - mono  # [not win]
    - cmake  # [win]
    - pkg-config >=0.21  # [not win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - swig
  host:
    - libgdal ={{ gdalversion }}
  run:
    - libgdal ={{ gdalversion }}
    - mono  # [not win]

test:
  commands:
    - mono $CONDA_PREFIX/lib/gdal_test.exe  # [not win]
    - gdal_test  # [win]

about:
  home: http://www.gdal.org
  license: MIT
  license_file: LICENSE.TXT
  summary: |
    GDAL is a translator library for raster and vector geospatial data formats that is released under an
    X/MIT style Open Source license by the Open Source Geospatial Foundation.
    This package provides the C# and Unity interface to the library.

extra:
  recipe-maintainers:
    - runette
    - bjornharrtell
